INSERT INTO PUBLIC.TRAVELER (NAME)
VALUES ('Jonas'),
       ('Petras');

INSERT INTO PUBLIC.ITEM (NAME, IS_MANDATORY, WEIGHT, PROVIDE_KILOMETERS)
VALUES ('Vandens 1kg buteliukas', false, 1, 10),
       ('Palapinė', true, 6, NULL);

INSERT INTO PUBLIC.TRAVEL (NAME, DISTANCE_KILOMETERS, TRAVELER_ID)
VALUES ('Prie juros', 150, 1),
       ('Prie ežero', 20, 2);